### ISSUE TITLE
Semantic Version not supported in packages.config

### ISSUE THREAD

**Issue by ghost** [awesome-inc/NuPlug#8]
using a semantic version in "version" attribute of the xml file which throws a NullReferenceException.

I have the following packages config for my application.

```
<package version="2.4.0-unstable.782" id="MyProjectReference" targetFramework="net452" />    
```

Calling the PackageManager with the "unstable"-version throws the null-pointer exception 

```
packageManager.InstallPackages(packagesConfig, false, true);
```

The issue seems to be the method "SemanticVersion.Parse" in PackageManagerExtension.

https://github.com/awesome-inc/NuPlug/blob/ab7d49d514adf3cda1c103bc3edf650b9c59225b/NuPlug/PackageManagerExtensions.cs#L16

**Comment by ghost** [comment]
fixed in version 0.4.1 with a custom semversion parser.

**Comment by mkoertgen** [comment]
Not a valid NuGet version is more suitable for this issue. Not a fix and should thus be reverted

**Comment by ghost** [comment]
The assumption was wrong. The given version is not a nuget semver. changes reverted.
